# Generated by Django 4.1.2 on 2022-10-18 16:58

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 10, 18, 16, 58, 41, 197510))),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual.color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual.carmodel')),
            ],
        ),
    ]
