# Generated by Django 4.1.2 on 2022-10-18 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 16, 59, 16, 168012)),
        ),
    ]
